"""Third dev build

Revision ID: d59d7f17b213
Revises: 
Create Date: 2022-01-29 05:58:47.631917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd59d7f17b213'
# schema='development'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS development;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_user',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('asof', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('displayname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followers_count', sa.BigInteger(), nullable=True),
    sa.Column('friends_count', sa.BigInteger(), nullable=True),
    sa.Column('listed_count', sa.BigInteger(), nullable=True),
    sa.Column('statuses_count', sa.BigInteger(), nullable=True),
    sa.Column('last_tweeted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='development'
    )
    op.create_index('idx_asof_desc', 'dt_user', [sa.text('asof DESC')], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_user_asof'), 'dt_user', ['asof'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_user_last_tweeted'), 'dt_user', ['last_tweeted'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_user_username'), 'dt_user', ['username'], unique=True, schema='development')
    op.create_table('dt_user_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=10001), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('asof', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('displayname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followers_count', sa.BigInteger(), nullable=True),
    sa.Column('friends_count', sa.BigInteger(), nullable=True),
    sa.Column('listed_count', sa.BigInteger(), nullable=True),
    sa.Column('statuses_count', sa.BigInteger(), nullable=True),
    sa.Column('last_tweeted', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='development'
    )
    op.create_index('idx_history_asof_desc', 'dt_user_history', [sa.text('asof DESC')], unique=False, schema='development')
    op.create_index('idx_history_asof_user_id', 'dt_user_history', ['asof', 'user_id'], unique=True, schema='development')
    op.create_index(op.f('ix_development_dt_user_history_asof'), 'dt_user_history', ['asof'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_user_history_last_tweeted'), 'dt_user_history', ['last_tweeted'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_user_history_username'), 'dt_user_history', ['username'], unique=False, schema='development')
    op.create_table('dt_status',
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=True),
    sa.Column('reply_count', sa.BigInteger(), nullable=True),
    sa.Column('retweet_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('quote_count', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.String(length=280), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('quoted_id', sa.BigInteger(), nullable=True),
    sa.Column('hashtags', sa.String(), nullable=True),
    sa.Column('mentions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['development.dt_user.id'], ),
    sa.PrimaryKeyConstraint('status_id'),
    schema='development'
    )
    op.create_index(op.f('ix_development_dt_status_conversation_id'), 'dt_status', ['conversation_id'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_status_created_at'), 'dt_status', ['created_at'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_status_lang'), 'dt_status', ['lang'], unique=False, schema='development')
    op.create_index(op.f('ix_development_dt_status_quoted_id'), 'dt_status', ['quoted_id'], unique=False, schema='development')
    op.drop_index('ix_dt_status_asof', table_name='dt_status')
    op.drop_table('dt_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dt_status',
    sa.Column('status_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('asof', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('status_id', name='dt_status_pkey')
    )
    op.create_index('ix_dt_status_asof', 'dt_status', ['asof'], unique=False)
    op.drop_index(op.f('ix_development_dt_status_quoted_id'), table_name='dt_status', schema='development')
    op.drop_index(op.f('ix_development_dt_status_lang'), table_name='dt_status', schema='development')
    op.drop_index(op.f('ix_development_dt_status_created_at'), table_name='dt_status', schema='development')
    op.drop_index(op.f('ix_development_dt_status_conversation_id'), table_name='dt_status', schema='development')
    op.drop_table('dt_status', schema='development')
    op.drop_index(op.f('ix_development_dt_user_history_username'), table_name='dt_user_history', schema='development')
    op.drop_index(op.f('ix_development_dt_user_history_last_tweeted'), table_name='dt_user_history', schema='development')
    op.drop_index(op.f('ix_development_dt_user_history_asof'), table_name='dt_user_history', schema='development')
    op.drop_index('idx_history_asof_user_id', table_name='dt_user_history', schema='development')
    op.drop_index('idx_history_asof_desc', table_name='dt_user_history', schema='development')
    op.drop_table('dt_user_history', schema='development')
    op.drop_index(op.f('ix_development_dt_user_username'), table_name='dt_user', schema='development')
    op.drop_index(op.f('ix_development_dt_user_last_tweeted'), table_name='dt_user', schema='development')
    op.drop_index(op.f('ix_development_dt_user_asof'), table_name='dt_user', schema='development')
    op.drop_index('idx_asof_desc', table_name='dt_user', schema='development')
    op.drop_table('dt_user', schema='development')
    # ### end Alembic commands ###
